use crate::error::AppError;
use std::sync::atomic::{AtomicU16, AtomicU64, Ordering};
use time::OffsetDateTime;
use tracing::{error, info};

#[derive(Debug)]
pub struct SnowflakeIdGenerator {
    machine_id: u16,
    sequence_number: AtomicU16,
    last_timestamp: AtomicU64,
}

impl SnowflakeIdGenerator {
    pub fn new(machine_id: u16) -> Self {
        Self {
            machine_id,
            sequence_number: AtomicU16::new(0),
            last_timestamp: AtomicU64::new(0), // 0 milliseconds from 1st May 2026
        }
    }

    pub fn generate(&self) -> Result<u64, AppError> {
        let current_timestamp = (OffsetDateTime::now_utc().unix_timestamp() * 1000) as u64;
        info!("Current timestamp :: {}", current_timestamp);
        let start_timestamp = 1782571067000u64; // Your custom epoch in milliseconds

        let current_offset = current_timestamp.saturating_sub(start_timestamp);
        info!("Current offset :: {}", current_offset);

        let last_ts = self.last_timestamp.load(Ordering::SeqCst);

        if current_offset == last_ts {
            // Same millisecond - increment sequence
            let seq = self.sequence_number.fetch_add(1, Ordering::SeqCst);
            if seq >= 4095 {
                // Overflow scenario: wait for next millisecond
                let mut next_offset = current_offset;
                while next_offset == last_ts {
                    // Spin wait or sleep briefly
                    std::thread::sleep(std::time::Duration::from_millis(1));
                    next_offset = OffsetDateTime::now_utc().millisecond() as u64 - start_timestamp;
                }
                // Update to new millisecond and reset sequence
                self.last_timestamp.store(next_offset, Ordering::SeqCst);
                self.sequence_number.store(0, Ordering::SeqCst);
                // Use the new offset for ID generation
                #[allow(clippy::identity_op)]
                let id = (next_offset << 22) | ((self.machine_id as u64) << 12) | 0;
                return Ok(id);
            }
        } else if current_offset < last_ts {
            // Clock went backward - this is a critical error
            error!("Clock drift detected!");
            return Err(AppError::ServerError);
        } else {
            // New millisecond - reset sequence
            self.last_timestamp.store(current_offset, Ordering::SeqCst);
            self.sequence_number.store(0, Ordering::SeqCst);
        }

        let id = (current_offset << 22)
            | ((self.machine_id as u64) << 12)
            | self.sequence_number.load(Ordering::SeqCst) as u64;

        info!("ID generated by snowflake generator :: {}", id);
        Ok(id)
    }
}
